travis:
  secure:
    BINSTAR_TOKEN: npfX5NcVuo9Cxd5zkP9teSaJ+Hs7kt4HBFFfRnV0egLeumW0/ofkmmVKBwss//Yo9VloIgDhcKtob1YuMFvEZEDNgSH57Ulg0I78zsR+vaxIj242sm2XFKbvf9cTkqNTuKOuHj0a3PQRe1SFk8xJEtGiqhV8+CsOpefYwFARN2S4Y8AUVCxHuruU9ljwjXTGnFzPF8JHH6q2jHzJCenHRApXrzxR9ByMBs0J7faU+4lqNkQqa3o0Jr7KVdWyDom8C4Rzvg0b2eqg1ztFlbXuv0pFM1bEm9n+uGHOhSLXuovWHs7tbHN/zJwHjkUyjachrUTFxzu9piRclYRHuAY7mPSzb06Z8+Hmww56P8LFkL81+SXS73oPJchpAyxxDZaCF5j/2U+FbJahomoHlhovE0WmeMfOeiXhEjBITMiMBD9BX28A+rRGwMu3WqD972lbVRsFBXNRCAaMjUcmWnP4+ddVW0a7w9vQdfVxUX23lWSK1Rh91LMeq+YLh/T6iN1XEZH6ZzRa/JJ074kwKyFZOWgOFUvm/YGfCM15v/Zicw200dlG9d68Az2r42TWpm8b5scZQOB0x00hnZtpmzxbjWfLKR1zFrRITdssI1IvdUzrO/WAtUzInbTMKpNhIKFHw0xEZxgdIkwep1m3lC02IWhcDSJsFIG8USN3Bt0ORWg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
