appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: aK7R127SOSI9K/kjSuC/tASTPQ2/GP1dfSD63jGfVstj5bI+47BTgE2CWiKl22iZto4h5mD0kWibA5TdmTOughaanXcMc/Smr04QLKes6Uj15x0JyoAx8TnMT+ja9VoRIDet8QljwmbsmsLJAFJrEgDHjA4UanrN1SOhkUd2zNhsXjdB7IMDXAwSqRcbUkZV/g6ypOfG6KXFujnTR27kvt026n3XR7IjrzBCDmYU6Biy+mELwnWIGkVfJxhNgSLUF/7aBz4HzkBii///MiLSSy7eD+5IbQ9wWwORyF+w6l654eseqoJQu61SExYXAt18xBi4Sd+YKcHgNJdYxWrQ6vlIyWjIL8quMg6OTwJq9xvnnkMm9HgGyUMZXB4newFI5aKzRNdwqlwqvPa+aHNpLPyFzCilu8m5amOsYSOhlGZtuousKICBOn8zUEPvB3i/lXis9KnWRVM5MmZ9kYfb6dosrS2gJm0B36Z3mDyP+bM8GwKES2XrjBiuRYTstTNIFlh3XZiLHHgLB+mC4w67y323yGuMWAyN+y/7qLdikScrhAvRkiZ/DIB29qyiEf1f9UyorzWIzICsUWDTUrBfKaUm8KXfSZb0iXKXOpgI5sDrtSUwCHtKjuqz8HGzm3VVDNy5kWwNETbD62Aizp4qlhNOFbv4hhCSHnuDI1lt63M=}
bot:
  automerge: true
